title: FIM docs
description: File Integrity Monitoring software documentation webpage
remote_theme: just-the-docs/just-the-docs@v0.4.1
color_scheme: light

url: https://documentation.achiefs.com

aux_links:
  Source Repository: https://github.com/Achiefs/fim
  Achiefs: https://achiefs.com

callouts:
  note:
    title: Note
    color: blue

ga_tracking: G-MTKBVPJR32
ga_tracking_anonymize_ip: true
