title: FIM docs
description: File Integrity Monitoring software documentation webpage
theme: just-the-docs
color_scheme: light

url: https://documentation.achiefs.com

aux_links:
  Source Repository: https://github.com/Achiefs/fim
  Achiefs: https://achiefs.com

callouts:
  note:
    title: Note
    color: blue

plugins:
  - jekyll-default-layout

ga_tracking: G-MTKBVPJR32
ga_tracking_anonymize_ip: true
